// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAopzBGe3r-rRZiWAWHmNKZJfmt9-jAfJA',
    appId: '1:736855576168:web:71413e84182202200ff5dd',
    messagingSenderId: '736855576168',
    projectId: 'test-firebase-253df',
    authDomain: 'test-firebase-253df.firebaseapp.com',
    databaseURL: 'https://test-firebase-253df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-firebase-253df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlCo88B24MFQFUqcn5NEC0OguXce0oEfI',
    appId: '1:736855576168:android:39ba55aba8586cb10ff5dd',
    messagingSenderId: '736855576168',
    projectId: 'test-firebase-253df',
    databaseURL: 'https://test-firebase-253df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-firebase-253df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6M6JFP_-2BduvYINXnTXhI4NdlhpA-7M',
    appId: '1:736855576168:ios:82d0286d8593d3410ff5dd',
    messagingSenderId: '736855576168',
    projectId: 'test-firebase-253df',
    databaseURL: 'https://test-firebase-253df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-firebase-253df.firebasestorage.app',
    iosClientId: '736855576168-500hcj002mn1osfpnq98acn4c5n0vt31.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFundamental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6M6JFP_-2BduvYINXnTXhI4NdlhpA-7M',
    appId: '1:736855576168:ios:82d0286d8593d3410ff5dd',
    messagingSenderId: '736855576168',
    projectId: 'test-firebase-253df',
    databaseURL: 'https://test-firebase-253df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-firebase-253df.firebasestorage.app',
    iosClientId: '736855576168-500hcj002mn1osfpnq98acn4c5n0vt31.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFundamental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAopzBGe3r-rRZiWAWHmNKZJfmt9-jAfJA',
    appId: '1:736855576168:web:85ced3f4bc42a67b0ff5dd',
    messagingSenderId: '736855576168',
    projectId: 'test-firebase-253df',
    authDomain: 'test-firebase-253df.firebaseapp.com',
    databaseURL: 'https://test-firebase-253df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-firebase-253df.firebasestorage.app',
  );

}