// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg9Xek1w46v62adUjv-Cpugg11YugjxpU',
    appId: '1:789499580838:web:9a03b0c5819db9b78aff67',
    messagingSenderId: '789499580838',
    projectId: 'news-firebase-cbb5a',
    authDomain: 'news-firebase-cbb5a.firebaseapp.com',
    storageBucket: 'news-firebase-cbb5a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABuuMe_QyEAwF-dZv7GeMqTArHq0TP8T0',
    appId: '1:789499580838:android:99bd63713cccc0a78aff67',
    messagingSenderId: '789499580838',
    projectId: 'news-firebase-cbb5a',
    storageBucket: 'news-firebase-cbb5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Hn-NCJCD3JiqOqFDi6iiaF2jKuo3KDo',
    appId: '1:789499580838:ios:8cc3159426e4b7078aff67',
    messagingSenderId: '789499580838',
    projectId: 'news-firebase-cbb5a',
    storageBucket: 'news-firebase-cbb5a.firebasestorage.app',
    iosClientId: '789499580838-om6fueaegtspts9qn35tldg7s4dtc7b1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFundamental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Hn-NCJCD3JiqOqFDi6iiaF2jKuo3KDo',
    appId: '1:789499580838:ios:8cc3159426e4b7078aff67',
    messagingSenderId: '789499580838',
    projectId: 'news-firebase-cbb5a',
    storageBucket: 'news-firebase-cbb5a.firebasestorage.app',
    iosClientId: '789499580838-om6fueaegtspts9qn35tldg7s4dtc7b1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFundamental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg9Xek1w46v62adUjv-Cpugg11YugjxpU',
    appId: '1:789499580838:web:3f4d9176257900b38aff67',
    messagingSenderId: '789499580838',
    projectId: 'news-firebase-cbb5a',
    authDomain: 'news-firebase-cbb5a.firebaseapp.com',
    storageBucket: 'news-firebase-cbb5a.firebasestorage.app',
  );
}
